# version: '3.1'

# services:
#   client:
#     build: ./client

#   mysql:
#     image: mysql
#     environment:
#       MYSQL_HOST: mysql
#       MYSQL_DATABASE: search_clients_ilya
#       MYSQL_USER: root
#       MYSQL_PASSWORD:
#       MYSQL_ROOT_PASSWORD:
#     ports:
#       - '3306:3306'
#     # expose:
#     #   - 3306
#     volumes:
#       - /var/lib/mysql
#     restart: always

#   server:
#     build: ./server
#     env_file:
#       - ./server/.env
#     ports:
#       - 8081:80
#     links:
#       - mysql:mysql
#     depends_on:
#       - mysql

# db:
#   image: mysql
#   restart: always
#   command: --default-authentication-plugin=mysql_native_password

# phpmyadmin:
#   image: phpmyadmin
#   restart: always
#   ports:
#     - 8080:80
#   environment:
#     - PMA_ARBITRARY=1

version: '3.8'

services:
  server:
    build:
      context: ./server
    env_file:
      - ./server/.env
    ports:
      - '5000:5000'
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=dbname
    restart: always

  # client:
  #   build: ./client
  #   ports:
  #     - '3000:3000'
  #   stdin_open: true
  #   tty: true
  #   restart: always
