export const birthdaysDE = [
  {
    day: 1,
    month: 5,
    text: [
      '1. Mai: Geburtstag unter dem Zeichen der Erneuerung und des Neuanfangs. Der 1. Mai ist ein Tag voller Leben und Symbolik. Die Sonne strahlt warm vom Himmel, die Natur erwacht zum Leben und die Luft ist erfüllt vom Duft von Maiglöckchen und frischer Erde. An diesem Tag, geboren unter dem Zeichen von Erneuerung, Neuanfang und Tatkraft, kommen Menschen auf die Welt, die die Welt mit ihrem Enthusiasmus und ihrer Willenskraft gestalten.',
      "Die Zahl '1' in der Numerologie symbolisiert: Neuanfang, Individualität und Führungskraft. Sie deutet darauf hin, dass Menschen, die am 1. Mai geboren wurden, einen starken Willen haben, gerne Verantwortung übernehmen und immer bereit sind, neue Herausforderungen anzugehen.",
      'Der Mai, der fünfte Monat des Jahres, ist nach der römischen Göttin Maia benannt, die für Wachstum und Fruchtbarkeit steht. Die Energie dieses Monats lädt Menschen mit Optimismus, Inspiration und Tatkraft auf.',
      'Persönlichkeiten, die am 1. Mai geboren wurden:',
      '•  Johann Sebastian Bach (deutscher Komponist),',
      '•  Mark Twain (amerikanischer Schriftsteller),',
      '•  Ayrton Senna (brasilianischer Rennfahrer),',
      '•  Oskar Kokoschka (österreichischer Maler und Grafiker),',
      '•  Audrey Hepburn (britische Schauspielerin),',
      '•  Tony Blair (britischer Politiker).',
      'Der 1. Mai ist ein Tag der Freude und des Neubeginns. Ich wünsche dir, dass dein Geburtstag voller Freude, Wärme und Liebe ist!',
    ],
  },
  {
    day: 2,
    month: 5,
    text: [
      '2. Mai: Geburtstag im Zeichen von Willenskraft und Sensibilität - an deinem Geburtstag, der im Frühling liegt, erblühst du mit neuer Kraft und Inspiration!',
      'Der 2. Mai ist ein Tag voller Licht und Leben. Die Sonne strahlt warm vom Himmel, die Natur erwacht zum Leben und die Luft ist erfüllt vom Duft von frischer Erde und blühenden Blumen. An diesem Tag, geboren unter dem Zeichen von Willenskraft, Sensibilität und Kreativität, kommen Menschen auf die Welt, die die Welt mit ihrem Enthusiasmus und ihrer Schaffenskraft gestalten.',
      "Die Zahl '2' in der Numerologie symbolisiert: Dualität, Partnerschaft und Harmonie. Diese Eigenschaften prägen Menschen, die am 2. Mai geboren wurden. Sie sind von Natur aus diplomatisch und harmoniebedürftig, besitzen aber gleichzeitig eine starke Willenskraft und Zielstrebigkeit.",
      'Der Mai, der fünfte Monat des Jahres, ist nach der römischen Göttin Maia benannt, die für Wachstum und Fruchtbarkeit steht. Die Energie dieses Monats inspiriert Menschen mit Optimismus, Kreativität und Lebensfreude.',
      'Berühmte Persönlichkeiten, die am 2. Mai geboren wurden: Katharina die Große (Zarin von Russland), Johann Wolfgang von Goethe (deutscher Dichter und Naturforscher), Arthur Schopenhauer (deutscher Philosoph).',
      'In einigen Kulturen wird der 2. Mai als Tag des Maibaumaufstellens und Feierns begangen. In anderen Kulturen wird der Geburtstag mit einem Festmahl und Geschenken gefeiert.',
      'Ich wünsche dir, dass dein Geburtstag voller Freude, Inspiration und Kreativität ist!',
    ],
  },
  {
    day: 3,
    month: 5,
    text: [
      '3. Mai: Geburtstag im Zeichen von Tatkraft und Lebensfreude - an deinem Geburtstag, der im Frühling liegt, sprießt neue Energie und Abenteuerlust!',
      'Der 3. Mai ist ein Tag voller Tatkraft und Lebensfreude. Die Sonne strahlt warm vom Himmel, die Vögel singen und die Natur erwacht zum Leben. An diesem Tag, geboren unter dem Zeichen von Tatkraft, Lebensfreude und Optimismus, kommen Menschen auf die Welt, die die Welt mit ihrem Enthusiasmus und ihrer Energie anstecken.',
      "Die Zahl '3' in der Numerologie symbolisiert: Kreativität, Kommunikation und Selbstvertrauen. Diese Eigenschaften prägen Menschen, die am 3. Mai geboren wurden. Sie sind von Natur aus kommunikativ und gesellig, besitzen aber gleichzeitig eine starke Willenskraft und Zielstrebigkeit.",
      'Der Mai, der fünfte Monat des Jahres, ist nach der römischen Göttin Maia benannt, die für Wachstum und Fruchtbarkeit steht. Die Energie dieses Monats inspiriert Menschen mit Optimismus, Lebensfreude und Mut.',
      'Berühmte Persönlichkeiten, die am 3. Mai geboren wurden: Arthur Schopenhauer (deutscher Philosoph) und Karl Marx (deutscher Philosoph und Ökonom).',
      'In einigen Kulturen ist der 3. Mai ein Tag, an dem man Maibäume aufstellt und feiert. In anderen Kulturen wird der Geburtstag mit einem Festmahl und Geschenken gefeiert.',
      'Ich wünsche dir, dass dein Geburtstag voller Freude, Tatkraft und Abenteuerlust ist!',
    ],
  },
  {
    day: 4,
    month: 5,
    text: [
      '4. Mai: Geburtstag im Zeichen von Freiheit und Unabhängigkeit - an deinem Geburtstag, der im Frühling liegt, entfaltest du deine Flügel und erkundest neue Horizonte!',
      'Der 4. Mai ist ein Tag voller Freiheit und Unabhängigkeit. Die Sonne strahlt warm vom Himmel, die Luft ist erfüllt vom Duft von frischer Erde und blühenden Blumen, und die Vögel singen ihr Lied. An diesem Tag, geboren unter dem Zeichen von Freiheit, Unabhängigkeit und Abenteuerlust, kommen Menschen auf die Welt, die die Welt mit ihrem Enthusiasmus und ihrer Neugierde erobern.',
      "Die Zahl '4' in der Numerologie symbolisiert: Stabilität, Ordnung und Erdung. Diese Eigenschaften prägen Menschen, die am 4. Mai geboren wurden. Sie sind von Natur aus diszipliniert und pflichtbewusst, besitzen aber gleichzeitig einen starken Freiheitsdrang und den Wunsch, die Welt zu erkunden.",
      'Die Energie dieses Monats inspiriert Menschen mit Optimismus, Lebensfreude und Mut.',
      'Berühmte Persönlichkeiten, die am 4. Mai geboren wurden: Audrey Hepburn (britische Schauspielerin und UNICEF-Botschafterin), George Lucas (US-amerikanischer Filmregisseur und -produzent) und Michelle Obama (US-amerikanische Rechtsanwältin und ehemalige First Lady der Vereinigten Staaten).',
      'In einigen Kulturen ist der 4. Mai ein Tag, an dem man Maibäume aufstellt und feiert. In anderen Kulturen wird der Geburtstag mit einem Festmahl und Geschenken gefeiert.',
      'Ich wünsche dir, dass dein Geburtstag voller Freiheit, Unabhängigkeit und Abenteuerlust ist!',
    ],
  },
  {
    day: 5,
    month: 5,
    text: [
      '5. Mai: Geburtstag im Zeichen von Neugier und Inspiration - an deinem Geburtstag, der im Frühling liegt, öffnest du dein Herz für neue Ideen und Inspiration!',
      'Der 5. Mai ist ein Tag voller Neugier und Inspiration. Die Sonne strahlt warm vom Himmel, die Natur erwacht zum Leben und die Luft ist erfüllt vom Duft von frischer Erde und blühenden Blumen. An diesem Tag, geboren unter dem Zeichen von Neugier, Inspiration und Kreativität, kommen Menschen auf die Welt, die die Welt mit ihrem Enthusiasmus und ihrer Fantasie bereichern.',
      "Die Zahl '5' in der Numerologie symbolisiert:",
      '- Veränderung: Sie steht für die Bereitschaft, neue Wege zu gehen und sich weiterzuentwickeln.',
      '- Freiheit: Sie repräsentiert das Streben nach Unabhängigkeit und Selbstbestimmung.',
      '- Abenteuerlust: Sie symbolisiert den Wunsch, die Welt zu erkunden und neue Erfahrungen zu machen.',
      'Diese Eigenschaften prägen Menschen, die am 5. Mai geboren wurden. Sie sind von Natur aus offen für Neues und suchen ständig nach Inspiration und Herausforderungen.',
      'Die Energie dieses Monats inspiriert Menschen mit:',
      '- Optimismus: Sie sehen die Welt mit einem positiven Blick und glauben an ihre Fähigkeiten.',
      '- Lebensfreude: Sie genießen die schönen Seiten des Lebens und feiern ihre Erfolge.',
      '- Mut: Sie scheuen sich nicht, Risiken einzugehen und neue Herausforderungen anzugehen.',
      'Berühmte Persönlichkeiten, die am 5. Mai geboren wurden:',
      '- Karl Marx: deutscher Philosoph und Ökonom',
      '- Florence Nightingale: britische Pionierin der Krankenpflege',
      '- Cinco de Mayo: mexikanischer Feiertag',
      'In einigen Kulturen ist der 5. Mai ein Tag, an dem man Maibäume aufstellt und feiert. In anderen Kulturen wird der Geburtstag mit einem Festmahl und Geschenken gefeiert.',
      'Ich wünsche dir, dass dein Geburtstag voller Neugier, Inspiration und Kreativität ist!',
    ],
  },
  {
    day: 6,
    month: 5,
    text: [
      '6. Mai: Geburtstag der Inspiration und des Einfühlungsvermögens',
      'Menschen, die am 6. Mai geboren wurden, zeichnen sich durch ihre inspirierende Art und ihr ausgeprägtes Einfühlungsvermögen aus. Sie sind natürliche Motivatoren, die andere mit ihrer Energie und ihrem Enthusiasmus anstecken können.',
      'Frühe Lerner und Wissensdurstige: Bereits in jungen Jahren zeigen sie eine große Neugierde und Wissensdurst. Sie sind schnelle Lerner und nehmen Informationen wie ein Schwamm auf. Diese Wissbegierde begleitet sie ihr Leben lang und macht sie zu vielseitigen und interessanten Gesprächspartnern.',
      'Kreative Visionäre und Umsetzer: Mit ihrem kreativen Kopf und ihrer innovativen Ader entwickeln sie oft visionäre Ideen. Sie zeichnen sich jedoch nicht nur durch ihre Ideenfindung aus, sondern besitzen auch die Fähigkeit, diese Ideen in die Tat umzusetzen. Mit Beharrlichkeit und Zielstrebigkeit verfolgen sie ihre Ziele und lassen sich von Rückschlägen nicht entmutigen.',
      'Empathische Zuhörer und verständnisvolle Freunde: Menschen, die am 6. Mai geboren wurden, besitzen ein ausgeprägtes Einfühlungsvermögen. Sie sind geduldige und verständnisvolle Zuhörer, die sich auf die Bedürfnisse und Emotionen anderer Menschen einstellen können. Freunde und Familie schätzen sie als loyale und vertrauenswürdige Ratgeber, die immer ein offenes Ohr für ihre Sorgen und Probleme haben.',
      'Liebhaber der Schönheit und Ästhetik: Sie haben einen ausgeprägten Sinn für Ästhetik und Schönheit. Dies zeigt sich sowohl in ihrem persönlichen Stil als auch in ihrer Liebe zu Kunst, Musik und Kultur. Sie genießen es, sich mit schönen Dingen zu umgeben und ihre Umgebung harmonisch zu gestalten.',
      'Geburtstag der Inspiration und des Einfühlungsvermögens: Menschen, die am 6. Mai geboren wurden, bereichern die Welt mit ihrer inspirierenden Art, ihrem Einfühlungsvermögen und ihrem kreativen Potenzial. Sie sind Motivatoren, Visionäre, verständnisvolle Freunde und konfliktlösende Persönlichkeiten, die die Welt durch ihre positive Einstellung und ihren Enthusiasmus zu einem schöneren Ort machen.',
      'Menschen, die am 6. Mai geboren wurden, sind einzigartige Persönlichkeiten, die mit ihren vielfältigen Talenten und Eigenschaften die Welt bereichern.',
      'Alles Gute zum Geburtstag!',
    ],
  },
  {
    day: 7,
    month: 5,
    text: [
      '7. Mai: Ein Tag voller Magie und Glück',
      'Der 7. Mai ist ein ganz besonderer Tag. Nicht nur, weil er im wunderschönen Monat Mai liegt, sondern auch, weil er Menschen mit einzigartigen Eigenschaften hervorbringt.',
      'Diejenigen, die am 7. Mai geboren wurden, fallen unter das Sternzeichen Stier. Stiere sind bekannt für ihre Zuverlässigkeit, Geduld und Willenskraft. Sie sind loyale Freunde, liebevolle Partner und fleißige Arbeiter.',
      'Magie und Glück - der 7. Mai selbst scheint von einer magischen Aura umgeben zu sein. Es ist ein Tag, der voller Freude und Optimismus ist. Menschen, die an diesem Tag geboren wurden, haben oft ein sonniges Gemüt und strahlen eine positive Energie aus, die ansteckend ist.',
      'Besondere Talente und Fähigkeiten',
      'Stiere, die am 7. Mai geboren wurden, haben oft besondere Talente und Fähigkeiten. Sie sind kreativ und intelligent, und sie haben ein ausgeprägtes Gespür für Ästhetik. Sie sind oft in der Kunst, Musik oder Literatur zu finden.',
      'Ein Leben voller Liebe und Erfolg',
      'Menschen, die am 7. Mai geboren wurden, haben oft ein glückliches und erfülltes Leben. Sie sind in der Regel sehr erfolgreich in ihrer Karriere und finden auch in der Liebe ihr Glück. Sie sind loyale Partner und hingebungsvolle Eltern.',
      'Prominente Geburtstagskinder',
      'Viele berühmte Persönlichkeiten wurden am 7. Mai geboren. Dazu gehören unter anderem:',
      '•	Johann Wolfgang von Goethe (deutscher Dichter und Dramatiker)',
      '•	Clara Schumann (Pianistin und Komponistin)',
      '•	Pyotr Ilyich Tchaikovsky (russischer Komponist)',
      '•	Audrey Hepburn (Schauspielerin und Stilikone)',
      '•	George Clooney (Schauspieler und Regisseur)',
      'Der 7. Mai ist ein Tag, der zum Feiern gemacht ist. Es ist ein Tag, um die Magie des Lebens zu genießen und die besonderen Menschen in unserem Leben zu schätzen.',
      'An alle, die am 7. Mai Geburtstag haben:',
      'Ihr seid etwas ganz Besonderes. Ihr habt die Kraft, die Welt mit eurer Liebe, eurem Lachen und eurer positiven Energie zu erhellen. Lasst euch an diesem Tag feiern und genießt all die schönen Dinge, die das Leben zu bieten hat.',
      'Der 7. Mai ist ein guter Tag, um etwas Neues zu beginnen, z. B. ein neues Hobby oder eine neue Herausforderung.',
      'Alles Gute zum Geburtstag!',
    ],
  },
  {
    day: 8,
    month: 5,
    text: [
      '8. Mai: Geburtstag im Zeichen von Willenskraft und Anmut - An deinem Geburtstag, der im Frühling liegt, schöpfst du neue Energie!',
      'Der 8. Mai ist ein Tag voller Leben und Symbolik. Die Sonne strahlt warm vom Himmel, die Natur erwacht zum Leben und die Luft ist erfüllt vom Duft von Maiglöckchen und frischer Erde. An diesem Tag, geboren unter dem Zeichen von Willenskraft, Anmut und Tatkraft, kommen Menschen auf die Welt, die die Welt mit ihrem Enthusiasmus und ihrer Willenskraft gestalten.',
      'Die Zahl "8" in der Numerologie symbolisiert:',
      '•	Erfolg: Sie steht für die Ernte der Früchte harter Arbeit und Zielstrebigkeit.',
      '•	Kraft: Sie repräsentiert die innere Stärke und das Durchhaltevermögen, um Herausforderungen zu meistern.',
      '•	Fülle: Sie symbolisiert das Potenzial für Wohlstand und Reichtum in allen Lebensbereichen.',
      'Diese Eigenschaften prägen Menschen, die am 8. Mai geboren wurden. Sie sind von Natur aus ehrgeizig und diszipliniert, scheuen aber auch keine harte Arbeit, um ihre Ziele zu erreichen. Der Mai, der fünfte Monat des Jahres, ist nach der römischen Göttin Maia benannt, die für Wachstum und Fruchtbarkeit steht. Die Energie dieses Monats inspiriert Menschen mit:',
      '•	Optimismus: Sie sehen die Welt mit einem positiven Blick und glauben an ihre Fähigkeiten.',
      '•	Kreativität: Sie finden neue und innovative Lösungen für Probleme.',
      '•	Lebensfreude: Sie genießen die schönen Seiten des Lebens und feiern ihre Erfolge.',
      'Die berühmte Persönlichkeiten, die am 8. Mai geboren wurden:',
      '•	Johann Wolfgang von Goethe: deutscher Dichter und Naturforscher',
      '•	Harry S. Truman: 33. Präsident der Vereinigten Staaten',
      '•	David Attenborough: britischer Naturforscher und Dokumentarfilmer',
      'In einigen Kulturen ist der 8. Mai ein Tag, an dem man Blumen pflückt und Maikränze bindet. In anderen Kulturen wird der Geburtstag mit einem Festmahl und Geschenken gefeiert',
      'Ich wünsche dir, dass dein Geburtstag voller Freude, Wärme und Liebe ist!',
    ],
  },
  {
    day: 9,
    month: 5,
    text: [
      '9. Mai: Geburtstag im Zeichen von Freiheit und Abenteuerlust - an deinem Geburtstag, der im Frühling liegt, brichst du auf zu neuen Horizonten!',
      'Der 9. Mai ist ein Tag voller Energie und Aufbruchstimmung. Die Sonne strahlt warm vom Himmel, die Vögel singen und die Natur erwacht zum Leben. An diesem Tag, geboren unter dem Zeichen von Freiheit, Abenteuerlust und Tatkraft, kommen Menschen auf die Welt, die das Leben in vollen Zügen genießen und die Welt mit ihrem Enthusiasmus anstecken. ',
      'Die Zahl "9" in der Numerologie symbolisiert:',
      '•	Abschluss: Sie steht für das Ende eines Zyklus und den Beginn eines neuen Kapitels.',
      '•	Transformation: Sie repräsentiert die Fähigkeit, sich weiterzuentwickeln und zu verändern.',
      '•	Weisheit: Sie symbolisiert das Wissen und die Erfahrung, die man im Laufe des Lebens gesammelt hat.',
      'Diese Eigenschaften prägen Menschen, die am 9. Mai geboren wurden. Sie sind von Natur aus neugierig und offen für Neues, und sie scheuen sich nicht, Risiken einzugehen, um ihre Ziele zu erreichen.',
      'Der Mai, der fünfte Monat des Jahres, ist nach der römischen Göttin Maia benannt, die für Wachstum und Fruchtbarkeit steht. Die Energie dieses Monats inspiriert Menschen mit:',
      '•	Optimismus: Sie sehen die Welt mit einem positiven Blick und glauben an ihre Fähigkeiten.',
      '•	Kreativität: Sie finden neue und innovative Lösungen für Probleme.',
      '•	Lebensfreude: Sie genießen die schönen Seiten des Lebens und feiern ihre Erfolge.',
      'Die berühmte Persönlichkeiten, die am 9. Mai geboren wurden:',
      '•	Johannes Kepler: deutscher Astronom und Naturforscher',
      '•	Sigmund Freud: Begründer der Psychoanalyse',
      '•	Billy Joel: US-amerikanischer Sänger und Songwriter',
      'In einigen Kulturen ist der 9. Mai ein Tag, an dem man Maibäume aufstellt und feiert. In anderen Kulturen wird der Geburtstag mit einem Festmahl und Geschenken gefeiert.',
      'Ich wünsche dir, dass dein Geburtstag voller Freude, Abenteuer und Entdeckergeist ist!',
    ],
  },
  {
    day: 10,
    month: 5,
    text: [
      '10. Mai: Kind des Frühlings - geboren unter dem Zeichen der Erneuerung.',
      'Ihr, die ihr am 10. Mai geboren wurdet, seid Kinder des Frühlings. In euch vereint sich die Kraft der Erneuerung mit der Leichtigkeit des Lebens.',
      'Der 10. Mai flüstert leise von Neuanfängen und dem Erwachen der Natur. An diesem Tag, umhüllt von der frischen Brise des Frühlings, erblicken Menschen das Licht der Welt, die von einem unbändigen Lebensmut und einer tiefen Verbindung zur Natur geprägt sind.',
      'Im Laufe der Geschichte haben die am 10. Mai Geborenen ihre Spuren in den unterschiedlichsten Bereichen hinterlassen:',
      '•	Johann Wolfgang von Goethe:** Der berühmte deutsche Dichter und Naturforscher, dessen Werke wie "Faust" und "Die Leiden des jungen Werther" bis heute die Weltliteratur prägen.',
      '•	Antonio Vivaldi:** Der italienische Komponist, dessen "Vier Jahreszeiten" die Farben und Stimmungen des Frühlings auf einzigartige Weise einfangen.',
      '•	Nikola Tesla:** Der serbische Erfinder und Physiker, dessen visionäre Ideen die ',
      'Elektrizitätstechnologie revolutionierten.',
      '•	Sigmund Freud:** Der Begründer der Psychoanalyse, der die menschliche Psyche erforschte und neue Wege zur Heilung seelischer Leiden erschloss.',
      '•	Atatürk:** Der Gründer der modernen Türkei, der sein Land mit Reformen in die Moderne führte.',
      '•	Nelson Mandela:** Der südafrikanische Freiheitskämpfer und erste schwarze Präsident Südafrikas, der gegen die Apartheid kämpfte und ein vereintes Land schuf.',
      'So unterschiedlich ihre Lebenswege und Errungenschaften auch sein mögen, die am 10. Mai Geborenen teilen doch einige Gemeinsamkeiten:',
      '•	Neugier und Wissensdurst - sie alle sind von einem unbändigen Wissensdurst getrieben und suchen ständig nach neuen Herausforderungen und Lernmöglichkeiten.',
      '•	Kreativität und Innovationsgeist - Ihre sprudelnde Fantasie und ihr innovativer Geist inspirieren andere und bringen neue Ideen in die Welt.',
      '•	Optimismus und Lebensfreude - Sie blicken mit Zuversicht in die Zukunft und lassen sich von Rückschlägen nicht entmutigen.',
      '•	Empathie und Mitgefühl - Sie sind tief mit ihren Mitmenschen verbunden und setzen sich für Gerechtigkeit und ein friedliches Miteinander ein.',
      'Der 10. Mai ist ein Tag der Freude und des Neubeginns. Lasst uns die Kraft des Frühlings in uns tragen und die Welt mit unseren Talenten und unserer Liebe bereichern!',
      'Alles Gute zum Geburtstag!',
    ],
  },
];
